backbone: 'ViT-B/16'
datasets: ["eurosat", "organamnist", "artbench10-256", "mnist", "oxford_flowers", "aircraft", "galaxy10-decals", "dtd"]

data_root: ./data
batch_size: 128
num_workers: 8

augmentation_time: 1
