backbone: 'ViT-B/16'
datasets: ["artbench10-256", "mnist", "organamnist", "aircraft", "eurosat", "dtd", "galaxy10-decals", "oxford_flowers"]

data_root: ./data
batch_size: 128
num_workers: 8

augmentation_time: 1
